import { LegalLayout } from "@/components/layout/legal-layout";

export default function PrivacyPolicy() {
  return (
    <LegalLayout title="Privacy Policy" lastUpdated="December 17, 2025">
      <section>
        <p className="text-lg text-muted-foreground">
          Renard ("we", "our", or "the Service") is a developer productivity
          platform designed to help you capture, organize, and recall your
          interactions with AI Large Language Models (LLMs). This policy
          outlines how we handle data across our ecosystem, including our{" "}
          <strong>Browser Extensions</strong>, <strong>CLI Tools</strong>, and{" "}
          <strong>IDE Extensions</strong> (VS Code, Cursor).
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-bold mb-4 text-foreground">
          1. Information We Collect
        </h2>
        <p className="mb-4">
          Renard collects only the data strictly necessary to provide its core
          functionality: creating a unified history of your AI development work.
        </p>

        <div className="pl-4 border-l-2 border-primary/20 space-y-6">
          <div>
            <h3 className="font-semibold text-foreground mb-2">
              A. Developer Interactions (User Content)
            </h3>
            <p>Across all our tools, we capture:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-muted-foreground ml-2">
              <li>
                <strong>Prompts & Inputs:</strong> The text you type into
                supported LLM interfaces or CLIs.
              </li>
              <li>
                <strong>Model Responses:</strong> The output generated by the AI
                model.
              </li>
              <li>
                <strong>Metadata:</strong> Timestamps, model names (e.g., GPT-4,
                Claude 3.5), and tool identifiers.
              </li>
              <li>
                <strong>Session Context:</strong> How individual messages relate
                to a conversation thread.
              </li>
            </ul>
          </div>

          <div>
            <h3 className="font-semibold text-foreground mb-2">
              B. CLI & File System Access
            </h3>
            <p>
              When you install the <strong>Renard CLI</strong> (`renard`), you
              explicitly grant it permission to read specific log files on your
              local machine to function:
            </p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-muted-foreground ml-2">
              <li>
                <strong>Claude CLI:</strong> Reads from{" "}
                <code>~/.claude/projects/</code> to sync conversation history.
              </li>
              <li>
                <strong>Gemini CLI:</strong> Reads from{" "}
                <code>~/.gemini/tmp/*/chats/</code> to capture session data.
              </li>
              <li>
                <strong>OpenAI / Generic:</strong> Captures standard output
                (stdout/stdin) during interactive sessions initiated via the
                `renard` wrapper.
              </li>
            </ul>
            <p className="mt-2 text-sm italic text-muted-foreground">
              Note: We do not scan your entire hard drive. Access is strictly
              limited to the paths required for the supported tools.
            </p>
          </div>

          <div>
            <h3 className="font-semibold text-foreground mb-2">
              C. Account Information
            </h3>
            <p>
              To synchronize data across devices, we collect your email address,
              authentication tokens, and basic profile information from your
              chosen identity provider (GitHub or Google).
            </p>
          </div>
        </div>
      </section>

      <section>
        <h2 className="text-2xl font-bold mb-4 text-foreground">
          2. Backend Validation & Safety Layer
        </h2>
        <p className="mb-4">
          We understand that developer environments may contain sensitive data.
          Renard employs a strict <strong>Server-Side Validation Layer</strong>{" "}
          before storing any data:
        </p>

        <div className="bg-secondary/30 p-6 rounded-xl border border-border">
          <ul className="space-y-3">
            <li className="flex gap-3">
              <span className="text-green-500 font-bold">✅</span>
              <span>
                <strong>Allowed:</strong> Developer-context data, code snippets,
                architectural discussions, and debugging logs.
              </span>
            </li>
            <li className="flex gap-3">
              <span className="text-red-500 font-bold">❌</span>
              <span>
                <strong>Rejected:</strong> The system automatically rejects
                identifiable PII (Personally Identifiable Information),
                financial data, or content classified as non-developer context.
              </span>
            </li>
          </ul>
        </div>
      </section>

      <section>
        <h2 className="text-2xl font-bold mb-4 text-foreground">
          3. How We Use Your Data
        </h2>
        <p>Your data is used exclusively for:</p>
        <ul className="list-disc list-inside space-y-2 text-muted-foreground mt-2">
          <li>
            <strong>Synchronization:</strong> Making your CLI logs visible in
            your Web Dashboard.
          </li>
          <li>
            <strong>Search & Recall:</strong> Indexing your history so you can
            perform semantic searches (e.g., "How did I fix that React bug
            yesterday?").
          </li>
          <li>
            <strong>Summarization:</strong> Generating daily productivity
            summaries.
          </li>
        </ul>
        <p className="mt-4 font-medium">
          We strictly DO NOT use your code or conversation history to train
          public AI models.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-bold mb-4 text-foreground">
          4. Data Retention & Deletion
        </h2>
        <p className="mb-4">
          <strong>Local Storage:</strong> The Browser Extension and CLI store
          data locally in temporary buffers. These are cleared immediately after
          a successful sync to our servers.
        </p>
        <p className="mb-4">
          <strong>Cloud Storage:</strong> Data is retained according to your
          plan limits. You have the right to request full account deletion. Upon
          deletion, all your logs, vectors, and metadata are permanently
          scrubbed from our primary databases and vector stores.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-bold mb-4 text-foreground">5. Security</h2>
        <p>
          All data is transmitted via <strong>HTTPS (TLS 1.2+)</strong>. At
          rest, sensitive fields are encrypted. Our infrastructure runs on
          secure, SOC-2 compliant cloud providers (AWS). We employ strict access
          controls; Renard employees do not access your raw conversation logs
          unless explicitly authorized by you for support debugging.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-bold mb-4 text-foreground">
          6. Contact Us
        </h2>
        <p>
          If you have questions about this policy or the specific file paths
          accessed by our CLI, please contact us:
        </p>
        <div className="mt-4 p-4 border border-border rounded-lg inline-block">
          <p>
            <strong>Email:</strong>{" "}
            <a
              href="mailto:support@renard.live"
              className="text-primary hover:underline"
            >
              support@renard.live
            </a>
          </p>
          <p>
            <strong>Website:</strong>{" "}
            <a
              href="https://renard.live"
              className="text-primary hover:underline"
            >
              https://renard.live
            </a>
          </p>
        </div>
      </section>
    </LegalLayout>
  );
}
